replicaCount: 2

image:
  repository: docker.io/amburskui/httpserver
  tag: v0.3

domain: arch.homework

database:
  external: false

  # host: httpserver-database-chart
  # port: 5432
  # dbname: otusdb
  # username: postgres
  # password: password

  migration:
    enabled: true
    image:
      repository: docker.io/amburskui/httpserver-migrations
      tag: v0.3

httpserver-database-chart:
  default:
    data:
      port: 5432
      dbname: otusdb
      username: postgres
      password: password
