apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  database.host: {{ if .Values.database.host }}{{ .Values.database.host | quote }}{{ else }}"{{ .Release.Name }}-postgres-service"{{ end }}
  database.port: {{ .Values.database.port | quote }}
  database.database: {{ .Values.database.dbname | quote }} 
