apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  database.host: "{{ .Values.database.host }}"
  database.port: "{{ .Values.database.port }}"
  database.database: "{{ .Values.database.dbname }}"
