apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  database.username: {{ .Values.database.username | b64enc | quote }}
  database.password: {{ .Values.database.password | b64enc | quote }}
